language: python
python:
  - "3.6"
services:
   -  docker
before_script:
      -  pip install docker
      -  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
       

script:
  - docker build -t kyamajir123/travisdocker .
  - docker push kyamajir123/travisdocker:latest
